jhipster:
  image: jdubois/jhipster-docker:latest
  volumes:
    - $PWD/jhipster:/jhipster
  ports:
    - "8080:8080"
    - "3000:3000"
    - "3001:3001"
    - "4022:22"
  links:
    - mongo:mongo
    - mysql:mysql
    - postgres:postgres
    - elasticsearch:elasticsearch
    - hazelcast:hazelcast

postgres:
  image: postgres:9.4.4
  ports:
    - "127.0.0.1:5432:5432"
  volumes:
    - $PWD/pgdata:/var/lib/prostgresql/data

mongo:
  image: mongo:3.1
  ports:
    - "27017:27017"
  volumes:
    - $PWD/mongodata:/data/db

elasticsearch:
  image: elasticsearch:1.6
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - $PWD/esdata:/usr/share/elasticsearch/data

hazelcast:
  image: cacciald/hazelcast:latest
  ports:
    - "5701:5701"
    - "54327:54327/udp"

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - $PWD/mysqldata:/var/lib/mysql
  environment:
    MYSQL_PASS: "**ChangeMe**"
    MYSQL_ROOT_PASSWORD: "root"

