jhipster:
  image: jdubois/jhipster-docker:latest
  volumes:
    - $PWD/jhipster:/jhipster
  ports:
    - "8080:8080"
    - "3000:3000"
    - "3001:3001"
    - "4022:22"
  links:
    - mongo:mongo
    - postgres:postgres
    - elasticsearch:elasticsearch
    - cassandra:cassandra
    - hazelcast:hazelcast

postgres:
  image: postgres:9.4.4
  ports:
    - "5432:5432"
  volumes:
    - $PWD/pgdata:/var/lib/prostgresql/data

mongo:
  image: mongo:3.1
  ports:
    - "27017:27017"
  volumes:
    - $PWD/mongodata:/data/db

elasticsearch:
  image: elasticsearch:1.6
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - $PWD/esdata:/usr/share/elasticsearch/data

cassandra:
  image: cassandra:2.1.8
  ports:
    - "7000:7000"
  volumes:
    - $PWD/cassandra:/var/lib/cassandra/data

hazelcast:
  image: cacciald/hazelcast:latest
  ports:
    - "5701:5701"
    - "54327:54327/udp"
